// ─── User ────────────────────────────────────────────────────────────────────
export const currentUser = {
  id: "u1",
  name: "Alex Johnson",
  initials: "AJ",
  email: "alex.johnson@email.com",
  dob: "1988-04-12",
  age: 36,
  bloodType: "O+",
  height: "178 cm",
  weight: "71.2 kg",
  phone: "+1 (555) 234-8901",
  address: "42 Maple Street, Boston, MA 02101",
  emergencyContact: "Sarah Johnson · +1 (555) 234-8902",
  primaryDoctor: "Dr. Sarah Chen",
  insurance: "BlueCross BlueShield · #BCB-44821",
  healthScore: 84,
  memberSince: "March 2022",
};

// ─── Medicines ────────────────────────────────────────────────────────────────
export const medicines = [
  {
    id: "m1",
    name: "Metformin",
    genericName: "Metformin HCl",
    dosage: "500 mg",
    form: "Tablet",
    frequency: "Twice daily",
    times: ["8:00 AM", "8:00 PM"],
    prescriber: "Dr. Sarah Chen",
    condition: "Type 2 Diabetes",
    startDate: "2023-01-15",
    refillDate: "2024-07-01",
    pillsLeft: 24,
    totalPills: 60,
    takenToday: true,
    color: "#17998a",
    colorBg: "#edfaf7",
    category: "Antidiabetic",
    instructions: "Take with food. Avoid alcohol.",
    sideEffects: ["Nausea", "Stomach upset", "Diarrhea"],
    interactions: ["Alcohol", "Contrast dye"],
  },
  {
    id: "m2",
    name: "Lisinopril",
    genericName: "Lisinopril",
    dosage: "10 mg",
    form: "Tablet",
    frequency: "Once daily",
    times: ["12:00 PM"],
    prescriber: "Dr. Sarah Chen",
    condition: "Hypertension",
    startDate: "2022-08-20",
    refillDate: "2024-06-20",
    pillsLeft: 8,
    totalPills: 30,
    takenToday: false,
    color: "#7c3aed",
    colorBg: "#faf5ff",
    category: "ACE Inhibitor",
    instructions: "Take at the same time each day.",
    sideEffects: ["Dry cough", "Dizziness", "Headache"],
    interactions: ["NSAIDs", "Potassium supplements"],
  },
  {
    id: "m3",
    name: "Atorvastatin",
    genericName: "Atorvastatin Calcium",
    dosage: "20 mg",
    form: "Tablet",
    frequency: "Once daily",
    times: ["8:00 PM"],
    prescriber: "Dr. Michael Torres",
    condition: "High Cholesterol",
    startDate: "2023-03-10",
    refillDate: "2024-07-10",
    pillsLeft: 45,
    totalPills: 60,
    takenToday: false,
    color: "#d97706",
    colorBg: "#fffbeb",
    category: "Statin",
    instructions: "Can be taken at any time of day.",
    sideEffects: ["Muscle pain", "Liver enzyme changes"],
    interactions: ["Grapefruit juice", "Certain antibiotics"],
  },
  {
    id: "m4",
    name: "Vitamin D3",
    genericName: "Cholecalciferol",
    dosage: "2000 IU",
    form: "Softgel",
    frequency: "Once daily",
    times: ["8:00 AM"],
    prescriber: "Dr. Michael Torres",
    condition: "Vitamin D deficiency",
    startDate: "2023-06-01",
    refillDate: "2024-08-01",
    pillsLeft: 55,
    totalPills: 90,
    takenToday: true,
    color: "#2563eb",
    colorBg: "#eff6ff",
    category: "Supplement",
    instructions: "Take with a fatty meal for best absorption.",
    sideEffects: ["Rare at standard doses"],
    interactions: ["Thiazide diuretics"],
  },
];

// ─── Health Metrics ───────────────────────────────────────────────────────────
export const healthMetrics = {
  heartRate: { value: 72, unit: "bpm", status: "normal", ref: "60–100", trend: +2 },
  bloodPressure: { value: "118/76", unit: "mmHg", status: "normal", ref: "<120/80", trend: -4 },
  bloodGlucose: { value: 94, unit: "mg/dL", status: "normal", ref: "70–99", trend: -3 },
  bmi: { value: 22.4, unit: "kg/m²", status: "normal", ref: "18.5–24.9", trend: -0.1 },
  oxygenSat: { value: 98, unit: "%", status: "normal", ref: "95–100", trend: 0 },
  cholesterol: { value: 182, unit: "mg/dL", status: "normal", ref: "<200", trend: -8 },
  hba1c: { value: 5.4, unit: "%", status: "normal", ref: "<5.7", trend: 0 },
  weight: { value: 71.2, unit: "kg", status: "normal", ref: "68–78", trend: -0.3 },
};

export const metricsHistory = [
  { date: "Jun 8",  hr: 72, sbp: 118, dbp: 76, glucose: 94, weight: 71.2, o2: 98 },
  { date: "Jun 6",  hr: 70, sbp: 120, dbp: 78, glucose: 97, weight: 71.5, o2: 97 },
  { date: "Jun 4",  hr: 74, sbp: 122, dbp: 80, glucose: 91, weight: 71.4, o2: 98 },
  { date: "Jun 2",  hr: 68, sbp: 119, dbp: 77, glucose: 98, weight: 71.6, o2: 99 },
  { date: "May 30", hr: 75, sbp: 121, dbp: 79, glucose: 95, weight: 71.8, o2: 97 },
  { date: "May 28", hr: 71, sbp: 118, dbp: 76, glucose: 93, weight: 71.9, o2: 98 },
  { date: "May 25", hr: 73, sbp: 123, dbp: 81, glucose: 99, weight: 72.1, o2: 97 },
];

// Heart-rate sparkline (7 days, 24 points each)
export const hrSparkline = [68,70,69,72,74,71,70,73,75,72,70,68,71,74,76,73,71,70,72,74,73,71,70,72];

// ─── Notifications ────────────────────────────────────────────────────────────
export const notifications = [
  {
    id: "n1",
    type: "medication",
    title: "Lisinopril due now",
    body: "Your 12:00 PM dose of Lisinopril 10mg is ready.",
    time: "12:01 PM",
    date: "Today",
    read: false,
    priority: "high",
  },
  {
    id: "n2",
    type: "appointment",
    title: "Appointment tomorrow",
    body: "Follow-up with Dr. Sarah Chen at 10:30 AM — Boston Cardiac Center.",
    time: "9:00 AM",
    date: "Today",
    read: false,
    priority: "medium",
  },
  {
    id: "n3",
    type: "refill",
    title: "Lisinopril running low",
    body: "Only 8 pills remaining. Refill date: Jun 20. Contact Dr. Chen.",
    time: "8:00 AM",
    date: "Today",
    read: false,
    priority: "high",
  },
  {
    id: "n4",
    type: "lab",
    title: "Lab results available",
    body: "Your recent HbA1c panel results are ready to review.",
    time: "3:45 PM",
    date: "Yesterday",
    read: true,
    priority: "medium",
  },
  {
    id: "n5",
    type: "medication",
    title: "Morning medications taken",
    body: "Metformin 500mg and Vitamin D3 marked as taken.",
    time: "8:14 AM",
    date: "Yesterday",
    read: true,
    priority: "low",
  },
  {
    id: "n6",
    type: "health",
    title: "Weekly health summary ready",
    body: "Your health score improved by 2 points this week. View your report.",
    time: "9:00 AM",
    date: "Jun 3",
    read: true,
    priority: "low",
  },
];

// ─── Activity feed (dashboard) ────────────────────────────────────────────────
export const activityFeed = [
  { icon: "💊", text: "Took Metformin 500mg & Vitamin D3", time: "8:14 AM · Today",   colorBg: "#edfaf7" },
  { icon: "🩺", text: "Blood pressure logged: 118/76 mmHg", time: "7:52 AM · Today",   colorBg: "#f0fdf4" },
  { icon: "📅", text: "Appointment confirmed with Dr. Chen", time: "Yesterday",         colorBg: "#faf5ff" },
  { icon: "🔬", text: "HbA1c results received — 5.4%",      time: "Jun 6",             colorBg: "#fffbeb" },
  { icon: "⚖️", text: "Weight logged: 71.2 kg",             time: "Jun 6",             colorBg: "#eff6ff" },
];

// ─── Dashboard stats ──────────────────────────────────────────────────────────
export const dashboardStats = [
  { label: "Heart Rate",      value: "72",     unit: "bpm",   icon: "♥", iconBg: "#fff1f2", trend: "+2",  trendDir: "neutral", trendNote: "vs last week" },
  { label: "Blood Pressure",  value: "118/76", unit: "mmHg",  icon: "🩺", iconBg: "#f0fdf4", trend: "Opt", trendDir: "good",    trendNote: "optimal range" },
  { label: "Blood Glucose",   value: "94",     unit: "mg/dL", icon: "🩸", iconBg: "#fffbeb", trend: "−3",  trendDir: "good",    trendNote: "vs yesterday" },
  { label: "BMI",             value: "22.4",   unit: "kg/m²", icon: "⚖", iconBg: "#f5f3ff", trend: "−0.2",trendDir: "good",    trendNote: "this month" },
];